sudo: required
dist: trusty
language: python
python:
  - '3.4'

before_install:
  - pip install --upgrade pip

install:
  - pip install pylint
  - pip install coverage
  - pip install -r travis_requirements.txt

before_script:
  - uname -a
  - printenv | sort

script:
  - date
  - ls -al
  - make test
