sudo: required
dist: trusty
language: python
notifications:
  slack: rambofromburma:PFTNKrp0RiZB0xn8eKXx0MvJ
python:
  - '2.7.6'

before_install:
  - pip install --upgrade pip

install:
  - pip install pylint
  - pip install coverage
  - pip install Flask
  - pip install Flask-SQLAlchemy
  - pip install Flask-Testing
  - pip install Jinja2
  - pip install MarkupSafe
  - pip install SQLAlchemy
  - pip install Werkzeug
  - pip install argparse
  - pip install click
  - pip install itsdangerous
  - pip install wsgiref
  - pip install autopep8

before_script:
  - echo "before script"

script:
  - date
  - ls -al
  - make test
